# Generated by Django 2.1.3 on 2018-12-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profil_picture',
            field=models.ImageField(default='static/images/profil_picture', upload_to='static/images/profil_pictures'),
        ),
    ]
