# Generated by Django 2.1.3 on 2018-12-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_maillot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maillot',
        ),
    ]
