# Generated by Django 2.1.3 on 2018-12-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_maillot'),
        ('shop_app', '0010_comment_product'),
    ]

    operations = [
    ]
