# Generated by Django 2.1.3 on 2018-12-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_merge_20181217_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=52)),
                ('text', models.TextField()),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_app.Product')),
            ],
        ),
    ]
