# Generated by Django 2.1.3 on 2018-12-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0014_auto_20181217_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('text', models.TextField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Question')),
            ],
        ),
    ]
