# Generated by Django 2.1.3 on 2018-12-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response',
            new_name='question',
        ),
    ]
