# Generated by Django 2.1.3 on 2018-12-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=52)),
                ('email', models.EmailField(max_length=264)),
                ('text', models.TextField()),
            ],
        ),
    ]
